<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mola_viz_imgui</name>
  <version>3.2.0</version>
  <description>Dear ImGui (docking branch) GUI backend for MOLA</description>

  <maintainer email="joseluisblancoc@gmail.com">Jose-Luis Blanco-Claraco</maintainer>
  <license file="LICENSE">GPLv3</license>

  <url type="website">https://github.com/MOLAorg/mola/tree/develop/mola_viz_imgui</url>

  <!-- Runtime deps -->
  <depend>mola_kernel</depend>
  <depend>mrpt_maps</depend>
  <depend>mrpt_opengl</depend>
  <depend>mrpt_obs</depend>
  <depend>mrpt_gui</depend>
  <depend>mrpt_viz</depend>
  <depend>mrpt_imgui</depend>

  <depend>libglfw3-dev</depend>

  <!-- Dear ImGui is a git submodule built internally; no system package needed -->

  <doc_depend>doxygen</doc_depend>

  <buildtool_depend>cmake</buildtool_depend>
  <export>
    <build_type>cmake</build_type>
  </export>

</package>
