#!/bin/bash

if [ -z "$1" ]; then
	echo "Error: Usage is $0 <COMMAND>"
	exit 1	
fi

CWD=$(pwd);
ls -1d */.git | xargs -I FIL dirname FIL |
while read line; do
 echo
 echo "Running on: $line";
 echo "----------------------------------------";
 cd $CWD/$line;
 $@ ;
done;

