# This file defines parameters to configure the settings of the class
# PFLocalizationCore inside the ROS 2 package mrpt_pf_localization.
# Refer to the package README.md and the comments below for the meaning of each
# parameter.
#
# The two top-level entries are there so we can use this file as a ROS 2
# parameter YAML file, but it can be also used directly to feed the internal
# PFLocalizationCore class skipping those two top-level YAML maps, as done
# in the unit tests (see "test/*.cpp")
#
/**:
  ros__parameters:
    # If false (default), will use 2D (SE(2)) particle filter.
    # Otherwise,the 3D mode (SE(3)) is enabled.
    use_se3_pf: true

    # Execution rate (in Hz) of the particle filter main loop:
    rate_hz: 4.0

    # Particle density (particles/m²) upon initialization:
    initial_particles_per_m2: 20

    # You can include the initial pose here as parameter, or send it via a topic or service.
    initial_pose:
      # Mean (center) of initial pose
      mean: { x: 0.0, y: 0.0, z: 0.0, yaw: 0.0, pitch: 0.0, roll: 0.0 }
      std_x: 5.0     # 1 sigma uncertainty [meters]
      std_y: 5.0
      std_z: 0.0
      std_yaw: 6.0     # 1 sigma uncertainty [radians]
      std_pitch: 0.0
      std_roll: 0.0

    # Shows a live 3D window with the state of the PF, the map, sensors, etc.
    gui_enable: false
    gui_camera_follow_robot: true
    
    # For SE(2) mode: Uncertainty motion model for regular odometry-based motion
    # See docs for mrpt::obs::CActionRobotMovement2D::TMotionModelOptions or https://docs.mrpt.org/reference/latest/tutorial-motion-models.html
    motion_model_2d:
      modelSelection: mmGaussian    # (mmGaussian|mmThrun)
      gaussianModel:
        a1: 0.1    # [m/m]
        a2: 0.001  # [m/rad]
        a3: 2.0     # [deg/m]
        a4: 0.2    # [deg/deg]
        minStdXY: 0.01  # [m]
        minStdPHI: 0.2  # [deg]
      thrunModel:
        alfa1_rot_rot: 0.1
        alfa2_rot_trans: 0.1
        alfa3_trans_trans: 0.1
        alfa4_trans_rot: 0.1
        additional_std_XY: 0.01 # [m]
        additional_std_phi: 0.2 # [deg]

    # For SE(2) mode: Uncertainty motion model to use when NO odometry has
    # been received.
    # See docs for mrpt::obs::CActionRobotMovement2D::TMotionModelOptions or https://docs.mrpt.org/reference/latest/tutorial-motion-models.html
    motion_model_no_odom_2d:
      modelSelection: mmGaussian    # (mmGaussian|mmThrun)
      gaussianModel:
        minStdXY: 0.10  # [m]
        minStdPHI: 2.0  # [deg]
    
    # For SE(3) mode: Uncertainty motion model for regular odometry-based motion
    motion_model_3d:
      modelSelection: mmGaussian
    
    # For SE(3) mode: Uncertainty motion model to use when NO odometry has
    # been received.
    motion_model_no_odom_3d:
      modelSelection: mmGaussian

    # If set to true, the PF will not be initialized until:
    # - A map is provided with georeferencing information, and
    # - The first GNNS observation arrives (with a GGA datum)
    initialize_from_gnns: true

    # (the ROS topic to listen for GNNS is ser via a launch argument)


    # Particle filter options:
    # Refer to docs for: [TParticleFilterOptions](https://docs.mrpt.org/reference/latest/struct_mrpt_bayes_CParticleFilter_TParticleFilterOptions.html)
    # -----------------------------------------------
    pf_options:
      # Perform adaptive sample size? (KLD algorithm)
      adaptiveSampleSize: true
      
      # Resampling of particles will be performed when ESS < BETA. [0.0, 1.0]
      BETA: 0.5
      
      # Options: pfStandardProposal | pfAuxiliaryPFStandard | pfOptimalProposal | pfAuxiliaryPFOptimal
      PF_algorithm: pfStandardProposal
      
      # Options: prMultinomial | prResidual | prStratified | prSystematic
      resamplingMethod: prMultinomial
      
      # For the next params, refer to the upstream docs above for TParticleFilterOptions
      # (probably no need to change them)
      pfAuxFilterOptimal_MaximumSearchSamples: 100
      powFactor: 1.0
      max_loglikelihood_dyn_range: 15
      pfAuxFilterStandard_FirstStageWeightsMonteCarlo: false
      pfAuxFilterOptimal_MLE: false
    
    # Dynamic sample size options.
    # Refer to docs for [mrpt::slam::TKLDParams](https://docs.mrpt.org/reference/latest/class_mrpt_slam_TKLDParams.html)
    # and to Dieter Fox's paper: 
    #    Fox, D. (2003). Adapting the sample size in particle filters through
    #    KLD-sampling. The international Journal of robotics research, 22(12), 985-1003.
    # -----------------------------------------------------------------------------------
    kld_options:
      KLD_minSampleSize: 250
      KLD_maxSampleSize: 1000
      KLD_binSize_XY: 0.05    # [meters]
      KLD_binSize_PHI: 0.05   # [radians]
      KLD_delta: 0.05
      KLD_epsilon: 0.05
      KLD_minSamplesPerBin: 0

    # If defined, this block will override the likelihoodOptions field of the 
    # de-serialized metric map (.mm) used as global map:
    override_likelihood_point_maps:
      sigma_dist: 0.2  # [m]
      max_corr_distance: 3.0 # [m]
      decimation: 1
