/*               _
 _ __ ___   ___ | | __ _
| '_ ` _ \ / _ \| |/ _` | Modular Optimization framework for
| | | | | | (_) | | (_| | Localization and mApping (MOLA)
|_| |_| |_|\___/|_|\__,_| https://github.com/MOLAorg/mola

 Copyright (C) 2018-2026 Jose Luis Blanco, University of Almeria,
                         and individual contributors.
 SPDX-License-Identifier: GPL-3.0
 See LICENSE for full license information.
*/

/**
 * @file   ini2mm/main.cpp
 * @brief  CLI tool to overwrite the CLoadableOptions of the layers in a .mm file from a .ini file
 * @author Jose Luis Blanco Claraco
 * @date   Jun 18, 2026
 */

#include <mola_metric_maps/OptionsIniIO.h>
#include <mp2p_icp/metricmap.h>
#include <mrpt/config/CConfigFile.h>
#include <mrpt/system/filesystem.h>
#include <mrpt/system/os.h>

#include <CLI/CLI.hpp>
#include <iostream>
#include <stdexcept>

void run_ini2mm(
    const std::string& filInput, const std::string& filIni, const std::string& filOutput,
    const std::string& plugins)
{
  if (!plugins.empty())
  {
    std::string errMsg;
    std::cout << "Loading plugin(s): " << plugins << std::endl;
    if (!mrpt::system::loadPluginModules(plugins, errMsg))
    {
      throw std::runtime_error(errMsg);
    }
  }

  ASSERT_FILE_EXISTS_(filInput);
  ASSERT_FILE_EXISTS_(filIni);

  std::cout << "[ini2mm] Reading input map from: '" << filInput << "'..." << std::endl;

  mp2p_icp::metric_map_t mm;
  mm.load_from_file(filInput);

  std::cout << "[ini2mm] Read " << mm.layers.size() << " layer(s). Applying options from: '"
            << filIni << "'" << std::endl;

  const mrpt::config::CConfigFile cfg(filIni);

  size_t numUpdated = 0;
  for (auto& [layerName, layer] : mm.layers)
  {
    if (!layer)
    {
      continue;
    }

    const std::string classSectionKey = "class";
    if (cfg.sectionExists(layerName) && cfg.keyExists(layerName, classSectionKey))
    {
      const auto iniClass = cfg.read_string(layerName, classSectionKey, "");
      const auto mmClass  = std::string(layer->GetRuntimeClass()->className);
      if (!iniClass.empty() && iniClass != mmClass)
      {
        std::cerr << "[ini2mm] WARNING: layer '" << layerName << "' is of class '" << mmClass
                  << "' in the .mm file, but '" << iniClass << "' in the .ini file. Applying "
                  << "options anyway, matched by section name." << std::endl;
      }
    }

    std::vector<std::string> applied;
    std::vector<std::string> rejected;
    if (!mola::importMapLayerOptionsFromIni(*layer, cfg, layerName, &applied, &rejected))
    {
      std::cerr << "[ini2mm] WARNING: layer '" << layerName << "' has unsupported class '"
                << layer->GetRuntimeClass()->className << "', skipping it." << std::endl;
      continue;
    }

    for (const auto& s : rejected)
    {
      std::cerr << "[ini2mm] WARNING: layer '" << layerName << "': new creation options in [" << s
                << "] were REJECTED, since applying them would require discarding the "
                << "map's current contents (e.g. a voxel/grid size change). Left untouched."
                << std::endl;
    }

    if (applied.empty())
    {
      std::cout << "[ini2mm]  - layer '" << layerName
                << "': no matching sections found in the .ini file, left untouched." << std::endl;
      continue;
    }

    std::cout << "[ini2mm]  - layer '" << layerName << "' (" << layer->GetRuntimeClass()->className
              << "): updated " << applied.size() << " option group(s).";
    for (const auto& s : applied)
    {
      std::cout << " [" << s << "]";
    }
    std::cout << std::endl;

    numUpdated++;
  }

  std::cout << "[ini2mm] Saving updated map to: '" << filOutput << "'..." << std::endl;
  if (!mm.save_to_file(filOutput))
  {
    throw std::runtime_error("Could not save the output .mm file: '" + filOutput + "'");
  }

  std::cout << "[ini2mm] Done. Updated " << numUpdated << "/" << mm.layers.size() << " layer(s)."
            << std::endl;
}

int main(int argc, char** argv)
{
  try
  {
    CLI::App cli{"ini2mm: overwrite the options of the layers in a .mm file from a .ini file"};

    std::string argInput;
    cli.add_option("-i,--input", argInput, "Input metric map file (*.mm)")
        ->required()
        ->check(CLI::ExistingFile);

    std::string argIni;
    cli.add_option(
           "-c,--config", argIni, "Input configuration file (*.ini), as generated by mm2ini")
        ->required()
        ->check(CLI::ExistingFile);

    std::string argOutput;
    cli.add_option(
           "-o,--output", argOutput,
           "Output metric map file (*.mm). May be the same as --input to overwrite it.")
        ->required();

    std::string argPlugins;
    cli.add_option(
        "-l,--load-plugins", argPlugins,
        "One or more (comma separated) *.so files to load as plugins");

    try
    {
      cli.parse(argc, argv);
    }
    catch (const CLI::ParseError& e)
    {
      return cli.exit(e);
    }

    run_ini2mm(argInput, argIni, argOutput, argPlugins);
  }
  catch (const std::exception& e)
  {
    std::cerr << e.what() << std::endl;
    return 1;
  }
  return 0;
}
