version: 2
jobs:
  ros-rolling-u22.04:
    docker:
      - image: ros:rolling-ros-base
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run:
          name: Build with colcon
          command: |
            colcon build --symlink-install
workflows:
  version: 2
  build:
    jobs:
      - ros-rolling-u22.04
