version: 2
jobs:
  ros-rolling-u22.04:
    docker:
      - image: ros:rolling-ros-base
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive
      - run:
          name: Install rosdep dependencies
          command: |
            apt update # needed for rosdep - apt to get list of packages from ROS servers
            rosdep install --from-paths . --ignore-src -r -y
      - run:
          name: Build with colcon
          command: |
            source /opt/ros/*/setup.bash
            MAKEFLAGS="-j2" colcon build --symlink-install  --parallel-workers 2 --event-handlers console_direct+
workflows:
  version: 2
  build:
    jobs:
      - ros-rolling-u22.04
