# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

from datetime import datetime
import os
import re
import io
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.abspath('_ext'))

# sys.path.insert(1, os.path.abspath('/PATH/TO/doxyrest_b/doxyrest/sphinx'))
# JLBC: Must be added to PYTHONPATH manually by the caller.


# -- Project information -----------------------------------------------------

project = u'MOLA'
copyright = u'{year} The MOLA Authors.'.format(year=datetime.now().year)

xmlTree = ET.parse('../../mola/package.xml')
MOLA_VERSION = xmlTree.findtext('version')

# The short X.Y version
version = f'v{MOLA_VERSION}'
# The full version, including alpha/beta/rc tags
release = f'v{MOLA_VERSION}'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.mathjax',
    'sphinx_design',
    'sphinx_copybutton',
    #    'sphinx.ext.autosectionlabel',
    'sphinxcontrib.bibtex',
    'sphinxcontrib.mermaid',
]

# sphinxcontrib-mermaid options
mermaid_version = '11.4.0'
mermaid_output_format = 'raw'  # render via JS in the browser; keeps diagrams vector and diffable.

extensions += ['doxyrest', 'cpplexer']

bibtex_bibfiles = ['refs.bib']

# Show build time
html_last_updated_fmt = '%H:%M, %b %d, %Y'

# For edit on github:
html_context = {
    'display_github': True,
    'github_user': 'MOLAorg',
    'github_repo': 'mola',
    'github_version': 'develop/docs/source/'
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [u'_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = "sphinx_rtd_theme"

html_logo = 'imgs/mola-slam-logo.png'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [
    '_static',
]

# Custom JS/CSS for the MOLA ROS 2 cookbook parameter editor.
html_js_files = [
    'js/mola_cookbook.js',
]
html_css_files = [
    'css/mola_cookbook.css',
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'MOLAdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'MOLA.tex', u'MOLA Documentation',
     u'The MOLA Authors.', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'mola', u'MOLA Documentation',
     [u'The MOLA Authors.'], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'MOLA', u'MOLA Documentation',
     u'The MOLA Authors.', 'MOLA', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

PROJECT_CHANGELOGS = {
    "mola_bridge_ros2": "../../mola_bridge_ros2/CHANGELOG.rst",
    "mola_kernel": "../../mola_kernel/CHANGELOG.rst",
    "mola_lidar_odometry": "../../../mola_lidar_odometry/CHANGELOG.rst",
    "mola_metric_maps": "../../mola_metric_maps/CHANGELOG.rst",
    "mola_state_estimation_simple": "../../../mola_state_estimation/mola_state_estimation_simple/CHANGELOG.rst",
    "mola_state_estimation_smoother": "../../../mola_state_estimation/mola_state_estimation_smoother/CHANGELOG.rst",
    "mola_viz": "../../mola_viz/CHANGELOG.rst",
    "mp2p_icp": "../../../mp2p_icp/CHANGELOG.rst",
}


def _demote_headings_to_rubrics(text: str) -> str:
    lines = text.splitlines()
    out = []
    i = 0
    # common reST underline chars
    underline_re = re.compile(r'^[=\-~^"+`#*]{3,}\s*$')
    while i < len(lines):
        if i + 1 < len(lines) and underline_re.match(lines[i + 1]) and lines[i].strip():
            title = lines[i].strip()
            # replace any "Title\n------" with a rubric
            out.append(f'.. rubric:: {title}')
            out.append('')  # blank line after directives
            i += 2
        else:
            out.append(lines[i])
            i += 1
    return "\n".join(out) + "\n"


def build_tab_friendly_changelogs(app):
    gen_dir = os.path.join(app.srcdir, "_generated_changelogs")
    os.makedirs(gen_dir, exist_ok=True)
    for label, relpath in PROJECT_CHANGELOGS.items():
        src = os.path.normpath(os.path.join(app.srcdir, relpath))
        with io.open(src, "r", encoding="utf-8") as f:
            text = f.read()
        processed = _demote_headings_to_rubrics(text)
        dst = os.path.join(gen_dir, f"{label}.rst")
        with io.open(dst, "w", encoding="utf-8") as f:
            f.write(processed)


def setup(app):
    app.connect("builder-inited", build_tab_friendly_changelogs)
